package com.global.globalonline.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.global.globalonline.db.bean.DataSource;

import com.global.globalonline.db.dao.DataSourceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataSourceDaoConfig;

    private final DataSourceDao dataSourceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataSourceDaoConfig = daoConfigMap.get(DataSourceDao.class).clone();
        dataSourceDaoConfig.initIdentityScope(type);

        dataSourceDao = new DataSourceDao(dataSourceDaoConfig, this);

        registerDao(DataSource.class, dataSourceDao);
    }
    
    public void clear() {
        dataSourceDaoConfig.getIdentityScope().clear();
    }

    public DataSourceDao getDataSourceDao() {
        return dataSourceDao;
    }

}
