package com.global.globalonline.db.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table data.
 */
public class DataSource {

    private Long id;
    private String id_;
    private String name;
    private String ename;
    private String code;
    private String sort_id;
    private String shortname;
    private String word;
    private String logo;
    private String miniconfirm;
    private String withdraw_fee;
    private String minwithdrawbtc;
    private String maxwithdrawbtc;
    private String recharge_fee;
    private String draw_fee;
    private String bankname;
    private String bankno;
    private String bankadd;
    private String status;
    private String iswithdraw;
    private String module;

    public DataSource() {
    }

    public DataSource(Long id) {
        this.id = id;
    }

    public DataSource(Long id, String id_, String name, String ename, String code, String sort_id, String shortname, String word, String logo, String miniconfirm, String withdraw_fee, String minwithdrawbtc, String maxwithdrawbtc, String recharge_fee, String draw_fee, String bankname, String bankno, String bankadd, String status, String iswithdraw, String module) {
        this.id = id;
        this.id_ = id_;
        this.name = name;
        this.ename = ename;
        this.code = code;
        this.sort_id = sort_id;
        this.shortname = shortname;
        this.word = word;
        this.logo = logo;
        this.miniconfirm = miniconfirm;
        this.withdraw_fee = withdraw_fee;
        this.minwithdrawbtc = minwithdrawbtc;
        this.maxwithdrawbtc = maxwithdrawbtc;
        this.recharge_fee = recharge_fee;
        this.draw_fee = draw_fee;
        this.bankname = bankname;
        this.bankno = bankno;
        this.bankadd = bankadd;
        this.status = status;
        this.iswithdraw = iswithdraw;
        this.module = module;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getId_() {
        return id_;
    }

    public void setId_(String id_) {
        this.id_ = id_;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEname() {
        return ename;
    }

    public void setEname(String ename) {
        this.ename = ename;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getSort_id() {
        return sort_id;
    }

    public void setSort_id(String sort_id) {
        this.sort_id = sort_id;
    }

    public String getShortname() {
        return shortname;
    }

    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getMiniconfirm() {
        return miniconfirm;
    }

    public void setMiniconfirm(String miniconfirm) {
        this.miniconfirm = miniconfirm;
    }

    public String getWithdraw_fee() {
        return withdraw_fee;
    }

    public void setWithdraw_fee(String withdraw_fee) {
        this.withdraw_fee = withdraw_fee;
    }

    public String getMinwithdrawbtc() {
        return minwithdrawbtc;
    }

    public void setMinwithdrawbtc(String minwithdrawbtc) {
        this.minwithdrawbtc = minwithdrawbtc;
    }

    public String getMaxwithdrawbtc() {
        return maxwithdrawbtc;
    }

    public void setMaxwithdrawbtc(String maxwithdrawbtc) {
        this.maxwithdrawbtc = maxwithdrawbtc;
    }

    public String getRecharge_fee() {
        return recharge_fee;
    }

    public void setRecharge_fee(String recharge_fee) {
        this.recharge_fee = recharge_fee;
    }

    public String getDraw_fee() {
        return draw_fee;
    }

    public void setDraw_fee(String draw_fee) {
        this.draw_fee = draw_fee;
    }

    public String getBankname() {
        return bankname;
    }

    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    public String getBankno() {
        return bankno;
    }

    public void setBankno(String bankno) {
        this.bankno = bankno;
    }

    public String getBankadd() {
        return bankadd;
    }

    public void setBankadd(String bankadd) {
        this.bankadd = bankadd;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getIswithdraw() {
        return iswithdraw;
    }

    public void setIswithdraw(String iswithdraw) {
        this.iswithdraw = iswithdraw;
    }

    public String getModule() {
        return module;
    }

    public void setModule(String module) {
        this.module = module;
    }

}
